---
- name: Add Terraform Apt-Keys from URL
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true

- name: Add Terraform Repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    state: present
    filename: terraform
  become: true

- name: Install Terraform
  ansible.builtin.apt:
    pkg:
      - gnupg # Terraform dependency
      - terraform
    state: present
    update_cache: yes
  become: true
